from django.core.management.base import BaseCommand

from products.models import Brand, Category, Product

CATEGORIES = [
    {
        "name": "بذر و نشاء",
        "slug": "seeds",
        "tagline": "بذرهای آزمایش‌شده برای کشت حرفه‌ای.",
    },
    {
        "name": "خاک و کود آلی",
        "slug": "soil",
        "tagline": "بستر رشد پایدار برای مزرعه و گلخانه.",
    },
    {
        "name": "آبیاری",
        "slug": "irrigation",
        "tagline": "سامانه‌های قطره‌ای و تجهیزات مدیریت آب.",
    },
    {
        "name": "ابزار کشاورزی",
        "slug": "tools",
        "tagline": "ابزار کار مزرعه با دوام مناسب استفاده روزانه.",
    },
    {
        "name": "تغذیه گیاه",
        "slug": "plant-food",
        "tagline": "کود و مکمل برای رشد رویشی و زایشی.",
    },
    {
        "name": "گلخانه",
        "slug": "greenhouse",
        "tagline": "تجهیزات کنترل دما و استقرار نشاء.",
    },
    {
        "name": "باغ و باغستان",
        "slug": "orchard",
        "tagline": "نهال، قلمه و ملزومات باغداری.",
    },
    {
        "name": "زنبورداری",
        "slug": "apiary",
        "tagline": "تجهیزات زنبورستان و بذر گیاهان شهدزا.",
    },
]

BRANDS = [
    {"name": "کشت‌دریپ", "slug": "keshtdrip"},
    {"name": "پارت الکتریک", "slug": "part-electric"},
    {"name": "زردشت", "slug": "zardasht"},
    {"name": "پارس بذر", "slug": "pars-seed"},
    {"name": "البرز خاک", "slug": "alborz-soil"},
    {"name": "لالجین سفال", "slug": "laljin"},
    {"name": "مس زنجان", "slug": "zanjan-copper"},
    {"name": "ساوه نهال", "slug": "saveh-nursery"},
]

PRODUCTS = [
    {
        "category": "seeds",
        "name": "مخلوط بذر گوجه‌فرنگی",
        "slug": "sunset-tomato-mix",
        "blurb": "هشت رقم مناسب فضای باز و گلخانه با قوه نامیه کنترل‌شده.",
        "description": "این بسته برای واحدهای تولیدی تهیه شده است و شامل ارقام رایج بازار از جمله برندی‌واین، چروکی و سان‌گلد است. توصیه می‌شود شش هفته پیش از انتقال به زمین در سینی نشاء کشت شود. هر محموله با تاریخ تولید و نتیجه آزمون جوانه‌زنی همراه است.",
        "price": 185000,
        "unit": "۸ پاکت",
        "brand": "pars-seed",
        "badge": "پرفروش",
        "featured": True,
        "stock": 86,
    },
    {
        "category": "seeds",
        "name": "بذر گل ماه‌تاب",
        "slug": "night-bloom-moonflower",
        "blurb": "رقم رونده برای پوشش داربست و حاشیه گلخانه.",
        "description": "بذرها پیش از کشت یک شب در آب خیسانده شوند. مناسب مناطق معتدل و گرم. فاصله کاشت روی داربست حدود ۳۰ سانتی‌متر است.",
        "price": 98000,
        "unit": "پاکت",
        "brand": "pars-seed",
        "badge": "",
        "featured": False,
        "stock": 40,
    },
    {
        "category": "seeds",
        "name": "پیاز زعفران",
        "slug": "saffron-crocus-corms",
        "blurb": "بنه‌های درجه یک برای کشت پاییزه زعفران.",
        "description": "بیست بنه سالم با وزن مناسب کاشت. زمین باید زهکش مناسب داشته باشد. برداشت کلاله در مهر و آبان، صبح زود انجام می‌شود. مناسب واحدهای کوچک و مزارع تخصصی.",
        "price": 420000,
        "unit": "۲۰ بنه",
        "brand": "pars-seed",
        "badge": "فصلی",
        "featured": True,
        "stock": 24,
    },
    {
        "category": "soil",
        "name": "کمپوست رسیده",
        "slug": "black-gold-compost",
        "blurb": "کمپوست غربال‌شده برای اصلاح بافت خاک زراعی.",
        "description": "مواد آلی کاملاً پوسیده، بدون کود تازه. تا ۳۰ درصد حجم بستر قابل مخلوط است. برای باغ، مزرعه سبزی و گلدان‌های بزرگ مناسب است.",
        "price": 270000,
        "unit": "کیسه ۲۰ کیلوگرم",
        "brand": "alborz-soil",
        "badge": "",
        "featured": True,
        "stock": 60,
    },
    {
        "category": "soil",
        "name": "آجر کوکوپیت",
        "slug": "coco-coir-bricks",
        "blurb": "بستر سبک برای نشاءکاری و کشت گلخانه‌ای.",
        "description": "سه آجر فشرده پس از آبگیری حدود ۳۰ لیتر حجم می‌دهد. یک‌بار شست‌وشو توصیه می‌شود. با کمپوست مخلوط شود.",
        "price": 145000,
        "unit": "۳ آجر",
        "brand": "alborz-soil",
        "badge": "",
        "featured": False,
        "stock": 120,
    },
    {
        "category": "soil",
        "name": "مخلوط زهکش معدنی",
        "slug": "mineral-grit-mix",
        "blurb": "پوکه، بازالت و ماسه برای اصلاح خاک سنگین.",
        "description": "برای خاک رسی حدود ۲۰ درصد و برای گلدان مرکبات تا ۵۰ درصد مخلوط شود. دانه‌بندی یکنواخت و عاری از گرد زیاد.",
        "price": 210000,
        "unit": "۱۰ کیلوگرم",
        "brand": "alborz-soil",
        "badge": "",
        "featured": False,
        "stock": 55,
    },
    {
        "category": "irrigation",
        "name": "کیت قطره‌ای کشت‌دریپ",
        "slug": "keshtdrip-starter-kit",
        "blurb": "۳۰ متر لوله، کاهنده فشار و ۴۰ قطره‌چکان.",
        "description": "مجموعه پایه برای باغچه، گلخانه کوچک و ردیف گوجه‌فرنگی. به شیر معمولی متصل می‌شود. ابزار سوراخ‌کاری و اتصالات یدکی در بسته موجود است.",
        "price": 890000,
        "unit": "کیت",
        "brand": "keshtdrip",
        "badge": "محصول اصلی",
        "featured": True,
        "stock": 35,
    },
    {
        "category": "irrigation",
        "name": "کوزه سفالی آبیاری",
        "slug": "clay-olla-pots",
        "blurb": "آبیاری زیرسطحی با تبخیر کنترل‌شده.",
        "description": "یک جفت کوزه بدون لعاب. تا گردن در خاک قرار گیرد و هفته‌ای یک‌بار پر شود. مناسب گوجه‌فرنگی، فلفل و مرکبات گلدانی.",
        "price": 640000,
        "unit": "جفت",
        "brand": "laljin",
        "badge": "",
        "featured": True,
        "stock": 18,
    },
    {
        "category": "irrigation",
        "name": "سرشلنگ بارانی برنجی",
        "slug": "brass-rain-wand",
        "blurb": "پاشش یکنواخت برای نشاء و کرت‌های حساس.",
        "description": "سر برنجی با دسته چوبی. الگوی پاشش ملایم است و به گیاهچه آسیب نمی‌زند. اتصال استاندارد شیلنگ باغبانی.",
        "price": 540000,
        "unit": "عدد",
        "brand": "part-electric",
        "badge": "",
        "featured": False,
        "stock": 22,
    },
    {
        "category": "tools",
        "name": "کج‌بیل مسی",
        "slug": "copper-harvest-hoe",
        "blurb": "تیغه دست‌ساز برای وجین و سله‌شکنی.",
        "description": "لبه مسی با دسته Hickory. برای کار یک‌دستی در کرت مناسب است. پس از کار خشک شود. با گذشت زمان پاتین طبیعی می‌گیرد.",
        "price": 1250000,
        "unit": "عدد",
        "brand": "zanjan-copper",
        "badge": "",
        "featured": True,
        "stock": 16,
    },
    {
        "category": "tools",
        "name": "قیچی باغبانی تاشو",
        "slug": "folding-pruner",
        "blurb": "برش تمیز شاخه تا قطر ۱۲ میلی‌متر.",
        "description": "فولاد SK5، ضامن قفل و حلقه چرمی. پس از روزهای بارانی محور را روغن‌کاری کنید.",
        "price": 320000,
        "unit": "عدد",
        "brand": "zanjan-copper",
        "badge": "",
        "featured": False,
        "stock": 70,
    },
    {
        "category": "tools",
        "name": "جعبه برداشت چوبی",
        "slug": "cedar-harvest-crate",
        "blurb": "جعبه مشبک برای حمل میوه و سبزی.",
        "description": "ظرفیت حدود ۱۲ کیلوگرم. دیواره‌های مشبک تهویه محصول را حفظ می‌کند. دسته‌های طنابی فشار به کف دست وارد نمی‌کنند.",
        "price": 390000,
        "unit": "عدد",
        "brand": "zanjan-copper",
        "badge": "",
        "featured": False,
        "stock": 28,
    },
    {
        "category": "plant-food",
        "name": "محلول جلبک و ماهی",
        "slug": "kelp-fish-elixir",
        "blurb": "تغذیه برگی برای دوره رشد فعال.",
        "description": "جلبک فرآوری‌شده به‌همراه پروتئین هیدرولیز ماهی. رقت ۱۰ میلی‌لیتر در لیتر، هر دو هفته یک‌بار. تا ۴۸ ساعت پیش از برداشت محصولات خوراکی مصرف نشود.",
        "price": 260000,
        "unit": "۱ لیتر",
        "brand": "zardasht",
        "badge": "",
        "featured": False,
        "stock": 44,
    },
    {
        "category": "plant-food",
        "name": "پودر گل‌دهی",
        "slug": "bloom-dust",
        "blurb": "فرمول فسفر بالا برای تشکیل میوه.",
        "description": "فسفات طبیعی، زغال استخوان و بازالت. در شروع غنچه‌دهی پای قطره‌چکان گوجه‌فرنگی، کدو و درختان میوه مصرف شود.",
        "price": 195000,
        "unit": "۱٫۵ کیلوگرم",
        "brand": "zardasht",
        "badge": "",
        "featured": False,
        "stock": 50,
    },
    {
        "category": "greenhouse",
        "name": "کلوچ تاشو",
        "slug": "pop-up-cloche-trio",
        "blurb": "پوشش موقت برای محافظت نشاء در سرما.",
        "description": "سه پوشش تاشو با دریچه تهویه. در شب‌های یخبندان روی گیاهچه قرار گیرد. پس از جمع شدن حجم کمی اشغال می‌کند.",
        "price": 480000,
        "unit": "۳ عدد",
        "brand": "keshtdrip",
        "badge": "",
        "featured": False,
        "stock": 33,
    },
    {
        "category": "greenhouse",
        "name": "پد حرارتی نشاء",
        "slug": "seedling-heat-mat",
        "blurb": "گرم‌کننده زیرسینی برای جوانه‌زنی یکنواخت.",
        "description": "ابعاد مناسب دو سینی ۱۰۲۰. دمای بستر حدود ۲۴ درجه. برای فلفل و بادمجان با ترموستات استفاده شود.",
        "price": 720000,
        "unit": "عدد",
        "brand": "keshtdrip",
        "badge": "",
        "featured": False,
        "stock": 21,
    },
    {
        "category": "orchard",
        "name": "نهال انار پاکوتاه",
        "slug": "dwarf-pomegranate-whip",
        "blurb": "رقم مناسب باغچه و گلدان بزرگ.",
        "description": "نهال ریشه لخت حدود ۶۰ سانتی‌متر، پیوند روی پایه پاکوتاه. محل کاشت آفتاب‌گیر با زهکش مناسب. باردهی از سال دوم محتمل است.",
        "price": 980000,
        "unit": "نهال",
        "brand": "saveh-nursery",
        "badge": "فصلی",
        "featured": True,
        "stock": 12,
    },
    {
        "category": "orchard",
        "name": "بسته قلمه انجیر",
        "slug": "fig-cutting-bundle",
        "blurb": "چهار قلمه چوب سخت رقم شیرین.",
        "description": "قلمه‌ها در خواب زمستانه ارسال می‌شوند. ریشه‌زایی در ماسه یا گلدان سبک انجام شود. راهنمای یک‌برگی همراه محموله است.",
        "price": 240000,
        "unit": "۴ قلمه",
        "brand": "saveh-nursery",
        "badge": "",
        "featured": False,
        "stock": 40,
    },
    {
        "category": "apiary",
        "name": "مخلوط بذر گیاهان شهدزا",
        "slug": "wildflower-meadow-mix",
        "blurb": "پوشش حدود ۱۲ متر مربع برای زنبورستان.",
        "description": "شامل کیهان، شبدر، فاسلیا و شقایق. بدون بذر چمن پرکننده. در هوای خنک روی خاک لخت پاشیده شود.",
        "price": 175000,
        "unit": "۱۰۰ گرم",
        "brand": "pars-seed",
        "badge": "",
        "featured": False,
        "stock": 90,
    },
    {
        "category": "apiary",
        "name": "طبق کندوی لانگزتروث",
        "slug": "cedar-langstroth-super",
        "blurb": "طبق کم‌عمق استاندارد برای ذخیره عسل.",
        "description": "چوب سدر، اتصال فاق و زبانه. قاب جداگانه عرضه می‌شود تا نوع موم یا پلاستیک انتخاب شود.",
        "price": 1450000,
        "unit": "عدد",
        "brand": "keshtdrip",
        "badge": "",
        "featured": False,
        "stock": 9,
    },
]


class Command(BaseCommand):
    help = "بارگذاری فهرست نمونه محصولات"

    def handle(self, *args, **options):
        Category.objects.all().delete()
        Brand.objects.all().delete()
        cats = {}
        brands = {}
        for row in CATEGORIES:
            cats[row["slug"]] = Category.objects.create(**row)
        for row in BRANDS:
            brands[row["slug"]] = Brand.objects.create(**row)
        for row in PRODUCTS:
            data = dict(row)
            slug = data.pop("category")
            brand_slug = data.pop("brand")
            Product.objects.create(category=cats[slug], brand=brands[brand_slug], **data)
        self.stdout.write(self.style.SUCCESS(f"{len(cats)} دسته، {len(brands)} برند و {len(PRODUCTS)} محصول ثبت شد."))
