# Generated by Django 5.2.17 on 2026-09-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand_and_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='قیمت به تومان. اگر فشار کاری یا قطر تعریف شود، قیمت همان تنوع در فروشگاه نشان داده می\u200cشود.'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_pressure', models.CharField(blank=True, help_text='اختیاری. مثال: 4 بار', max_length=40, verbose_name='فشار کاری')),
                ('diameter', models.CharField(blank=True, help_text='اختیاری. مثال: 16 میلی\u200cمتر', max_length=40, verbose_name='قطر')),
                ('price', models.PositiveIntegerField(help_text='قیمت این ترکیب به تومان', verbose_name='قیمت')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع\u200cها',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'working_pressure', 'diameter'), name='unique_product_pressure_diameter')],
            },
        ),
    ]
