# Generated by Django 5.2.17 on 2026-09-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='showcase_image',
            field=models.ImageField(blank=True, help_text='تصویر اسلاید صفحه اصلی. جدا از تصویر کارت دسته است.', upload_to='categories/showcase/', verbose_name='تصویر ویترین'),
        ),
    ]
