# Generated by Django 5.2.17 on 2026-09-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_featured_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, help_text='متن کوتاه روی کارت محصول. مثال: پرفروش', max_length=40, verbose_name='برچسب'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='featured',
            field=models.BooleanField(default=False, help_text='این تنوع در ریل محصولات ویژه نشان داده می\u200cشود.', verbose_name='ویژه'),
        ),
    ]
